"use strict";
exports.__esModule = true;
var ducati_1 = require("./classes/ducati");
var mooney_1 = require("./classes/mooney");
var prima_1 = require("./classes/prima");
var aprilia_1 = require("./classes/aprilia");
var competition_1 = require("./classes/competition");
var quartararo_1 = require("./classes/quartararo");
var laps_1 = require("./classes/laps");
var decorator_1 = require("./classes/decorator");
var fb1 = new ducati_1.Ducati(270, 1, 'Francesco Bagnaia');
var jz5 = new prima_1.Prima(273, 5, 'Johann Zarco');
var lm10 = new mooney_1.Mooney(304, 10, 'Luca Marini');
var mv12 = new aprilia_1.Aprilia(250, 12, 'Maverick Viñales');
var fq20 = new quartararo_1.Quartararo('Fabio Quartararo', 218, 20);
// fb1.move();
// jz5.move();
// lm10.move();
// mv12.move();
var jarak = new laps_1.Laps();
jarak.setLaps(1000);
console.log(jarak.getLaps());
var totalJarak = new decorator_1.Decorator(jarak);
totalJarak.setLaps(12);
console.log(totalJarak.getLaps());
var motors = [fb1, jz5, lm10, mv12, fq20];
var competition = new competition_1.Competition(motors, 1200);
// competition.getMotor();
competition.race();
competition.winner();
